const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {test}=require('node:test');const {DatabaseSync}=require('node:sqlite');const ts=require('typescript');
const root=path.resolve(__dirname,'..');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},fileName:filename}).outputText,filename);
function fixture(t) {
 const previousWindow=global.window;global.window={__TAURI_INTERNALS__:{},navigator:{userAgent:'Android'}};const cache=new Map();
 const state={active:'owner-a',session:{authProvider:'supabase',user:{id:'owner-a'},token:'grant-fixture'},trusted:true,calls:[],cloud:new Map(),reject:new Map(),failAck:false};
 const mock=(name,exports)=>{const p=name.startsWith('.')?path.resolve(root,name):require.resolve(name);cache.set(p,require.cache[p]);require.cache[p]={id:p,filename:p,loaded:true,exports};};
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON; CREATE TABLE _sqlx_migrations(version INTEGER PRIMARY KEY,success INTEGER)');
 for(const [i,file] of ['0001_mobile_finance.sql','0002_mobile_planning.sql','0003_mobile_scheduling.sql','0004_mobile_cloud_pull.sql','0005_mobile_cloud_push.sql'].entries()){db.exec(fs.readFileSync(path.join(root,'src-tauri/migrations',file),'utf8'));db.prepare('INSERT INTO _sqlx_migrations VALUES(?,1)').run(i+1);}
 const bind=(sql,params=[])=>{const values=[];return{sql:sql.replace(/\$(\d+)/g,(_,n)=>{values.push(params[+n-1]);return '?';}),values};};
 mock('@tauri-apps/plugin-sql',{__esModule:true,default:{load:async()=>({select:async(sql,p)=>{const b=bind(sql,p);return db.prepare(b.sql).all(...b.values);},execute:async(sql,p)=>{const b=bind(sql,p),r=db.prepare(b.sql).run(...b.values);return{rowsAffected:Number(r.changes),lastInsertId:Number(r.lastInsertRowid)};},close:async()=>{}})}});
 mock('@tauri-apps/api/core',{invoke:async(name,{statements})=>{assert.equal(name,'mobile_sql_transaction');db.exec('BEGIN IMMEDIATE');try{const changed=statements.map(({sql,values,expected_rows},i)=>{if(state.failAck && sql.includes("SET sync_status=") && i===2)throw new Error('secret native path');const b=bind(sql,values),n=Number(db.prepare(b.sql).run(...b.values).changes);if(expected_rows!==undefined && expected_rows!==n)throw new Error('CAS');return n;});db.exec('COMMIT');return changed;}catch(error){db.exec('ROLLBACK');throw error;}}});
 const tables=['categorias','tags','metas_ahorro','gastos_programados','gastos_fijos','presupuestos','movimientos','movimiento_tags'];let clock=0;
 const bucket=owner=>{if(!state.cloud.has(owner))state.cloud.set(owner,{categorias:new Map(),movimientos:new Map()});return state.cloud.get(owner);};
 const remote=owner=>{const data=Object.fromEntries(tables.map(table=>[table,bucket(owner)[table]?[...bucket(owner)[table].values()]:[]]));const revisions=Object.values(data).flat().map(row=>row.remote_updated_at);return{ok:true,cursor:[`2026-10-06T12:00:00.${String(clock+1).padStart(6,'0')}+00:00`,...revisions].sort().at(-1),...data};};
 class CloudAuthRequestError extends Error{}
 mock('./services/cloudAuth.ts',{CloudAuthRequestError,getActiveOwnerId:()=>state.active,cloudRequest:async(route,options)=>{
  state.calls.push({route,method:options.method||'GET',body:options.body?JSON.parse(options.body):null});assert.equal(options.headers.Authorization,'Bearer grant-fixture');
  if(state.httpError)throw new Error('sensitive HTTP body');
  if(route.startsWith('/sync/pull'))return remote(state.session.user.id);
  assert.equal(route,'/sync/push');const body=JSON.parse(options.body),store=bucket(state.session.user.id),now=`2026-10-06T12:00:00.${String(++clock).padStart(6,'0')}+00:00`;
  const response={ok:true,accepted:Object.fromEntries(tables.map(k=>[k,[]])),rejected:[],counts:{},ignored:Object.fromEntries(tables.map(k=>[k,0])),conflicts:Object.fromEntries(tables.map(k=>[k,0])),device:{device_id:body.device_id,last_seen_at:now}};
  for(const table of tables){const rows=body[table];assert.ok(Array.isArray(rows));for(const row of rows){assert.equal(row.owner_user_id,undefined);assert.equal(row.local_change_version,undefined);
   const existing=store[table].get(row.sync_id);let rejection=state.reject.get(row.sync_id);
   // Exact existing cloud rule, including same-device retry exception.
   if(existing && row.last_remote_updated_at && row.last_remote_updated_at!==existing.remote_updated_at && existing.last_modified_device_id!==body.device_id)rejection='conflict_remote_newer';
   if(rejection){response.rejected.push({entity:table,sync_id:row.sync_id,code:rejection,message:'provider-sensitive'});response.ignored[table]++;if(rejection==='conflict_remote_newer')response.conflicts[table]++;}
   else {store[table].set(row.sync_id,{...row,remote_updated_at:now,last_modified_device_id:body.device_id});response.accepted[table].push(row.sync_id);}
  }response.counts[`${table}_received`]=rows.length;response.counts[`${table}_saved`]=response.accepted[table].length;}
  if(state.afterSend)await state.afterSend(body,response);
  if(state.loseResponse){state.loseResponse=false;throw new Error('timeout after commit');}
  if(state.corruptAck)response.counts.movimientos_saved=999;
  return response;
 }});
 mock('./services/supabaseCloudAuth.ts',{getSession:async()=>state.session});
 mock('./services/deviceAuthorization.ts',{listAccountDevices:async()=>state.trusted?[{current:true,status:'trusted',device_id:'android-device'}]:[]});
 for(const p of Object.keys(require.cache))if(p.startsWith(path.join(root,'services/data')))delete require.cache[p];
 const pull=require('../services/data/mobileCloudPull.ts'),push=require('../services/data/mobileCloudPush.ts'),finance=require('../services/data/mobileFinanceRepository.ts');
 t.after(()=>{db.close();global.window=previousWindow;for(const[p,value]of cache){if(value)require.cache[p]=value;else delete require.cache[p];}});
 const repo=owner=>finance.mobileAccountEntityRepository(owner);const row=(table,id)=>db.prepare(`SELECT * FROM ${table} WHERE sync_id=?`).get(id);
 async function create(owner='owner-a',description='prueba m9c'){const r=repo(owner);await r.createCategoria({nombre:`Gastos ${owner}`,tipo:'gasto'});const c=(await r.listCategorias())[0];await r.createMovimiento({fecha:'2026-10-06',tipo:'gasto',categoria_id:c.id,descripcion:description,monto:1234});return{category:db.prepare('SELECT * FROM categorias WHERE owner_user_id=?').get(owner),movement:db.prepare('SELECT * FROM movimientos WHERE owner_user_id=?').get(owner)};}
 return Object.assign(state,{db,pull,push,repo,row,create,remote,bucket});
}
test('no push without account or trusted device, local cannot be uploaded',async t=>{const s=fixture(t);await assert.rejects(s.push.pushMobileCloudNow('local'),{code:'invalid_owner'});await s.create();s.session=null;await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'session_required'});s.session={authProvider:'supabase',user:{id:'owner-a'},token:'grant-fixture'};s.trusted=false;await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'device_required'});assert.equal(s.calls.length,0);});
test('owner scope, pending selection, payload identity, category before movement and accepted ack',async t=>{const s=fixture(t);await s.create('local');await s.create('owner-b');const created=await s.create();const result=await s.push.pushMobileCloudNow('owner-a');assert.equal(result.uploaded,2);assert.equal(result.stillPending,0);const posts=s.calls.filter(c=>c.method==='POST');assert.equal(posts.length,2);assert.equal(posts[0].body.categorias.length,1);assert.equal(posts[0].body.movimientos.length,0);assert.equal(posts[1].body.movimientos[0].categoria_sync_id,created.category.sync_id);assert.equal(posts[1].body.movimientos[0].categoria_id,undefined);assert.equal(s.row('movimientos',created.movement.sync_id).sync_status,'synced');assert.equal(s.db.prepare("SELECT COUNT(*) n FROM movimientos WHERE owner_user_id IN ('local','owner-b') AND sync_status='pending'").get().n,2);});
test('unchanged M9B pull creates zero upload pending, raw revision retained',async t=>{const s=fixture(t);const raw='2026-10-06T11:00:00.123456+00:00';s.bucket('owner-a').categorias.set('downloaded',{sync_id:'downloaded',nombre:'Cloud',tipo:'gasto',created_at:raw,updated_at:raw,remote_updated_at:raw,deleted_at:null,last_modified_device_id:'pc'});await s.pull.applyMobilePull('owner-a',s.remote('owner-a'),null);assert.equal((await s.push.getMobileCloudPending('owner-a')).categorias.length,0);assert.equal(s.row('categorias','downloaded').last_remote_revision,raw);const before=s.calls.length;assert.equal((await s.push.pushMobileCloudNow('owner-a')).uploaded,0);assert.equal(s.calls.length,before);});
test('same batch twice and timeout after remote commit retry use same sync IDs',async t=>{const s=fixture(t),c=await s.create();s.loseResponse=true;await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'push_failed'});assert.equal(s.row('categorias',c.category.sync_id).sync_status,'pending');const ids=[c.category.sync_id,c.movement.sync_id];await s.push.pushMobileCloudNow('owner-a');assert.equal(s.bucket('owner-a').categorias.size,1);assert.equal(s.bucket('owner-a').movimientos.size,1);assert.deepEqual([s.row('categorias',ids[0]).sync_id,s.row('movimientos',ids[1]).sync_id],ids);const postCount=s.calls.filter(c=>c.method==='POST').length;await s.push.pushMobileCloudNow('owner-a');assert.equal(s.calls.filter(c=>c.method==='POST').length,postCount);});
test('partial success keeps rejected movement pending and records safe code',async t=>{const s=fixture(t),c=await s.create();s.reject.set(c.movement.sync_id,'invalid_payload');const r=await s.push.pushMobileCloudNow('owner-a');assert.equal(r.uploaded,1);assert.equal(r.rejected,1);assert.equal(s.row('categorias',c.category.sync_id).sync_status,'synced');assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'pending');assert.equal(s.row('movimientos',c.movement.sync_id).sync_error_code,'invalid_payload');s.reject.clear();assert.equal((await s.push.pushMobileCloudNow('owner-a')).uploaded,1);});
test('new category rejection prevents its movement from being sent',async t=>{const s=fixture(t),c=await s.create();s.reject.set(c.category.sync_id,'invalid_payload');const r=await s.push.pushMobileCloudNow('owner-a');assert.equal(r.rejected,2);assert.equal(s.calls.filter(c=>c.method==='POST').length,1);assert.equal(s.row('movimientos',c.movement.sync_id).sync_error_code,'category_rejected');assert.equal(s.bucket('owner-a').movimientos.size,0);});
test('newer cloud revision never overwrites silently and pull protects rejected edit',async t=>{const s=fixture(t),c=await s.create();await s.push.pushMobileCloudNow('owner-a');await s.repo('owner-a').updateMovimiento(c.movement.id,{fecha:c.movement.fecha,tipo:'gasto',categoria_id:c.category.id,descripcion:'local edit',monto:55});const remote=s.bucket('owner-a').movimientos.get(c.movement.sync_id);remote.descripcion='PC edit';remote.remote_updated_at='2026-10-06T12:00:00.999999+00:00';remote.last_modified_device_id='pc';const r=await s.push.pushMobileCloudNow('owner-a');assert.equal(r.conflicts,1);assert.equal(s.row('movimientos',c.movement.sync_id).descripcion,'local edit');assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'pending');await assert.rejects(s.pull.applyMobilePull('owner-a',s.remote('owner-a'),null),{code:'apply_failed'});assert.equal(await s.pull.getMobilePullCursor('owner-a'),null);assert.equal(s.row('movimientos',c.movement.sync_id).descripcion,'local edit');});
test('conflict between preflight and POST keeps local pending',async t=>{const s=fixture(t),c=await s.create();await s.push.pushMobileCloudNow('owner-a');await s.repo('owner-a').updateMovimiento(c.movement.id,{fecha:c.movement.fecha,tipo:'gasto',categoria_id:c.category.id,descripcion:'changed',monto:88});s.reject.set(c.movement.sync_id,'conflict_remote_newer');const r=await s.push.pushMobileCloudNow('owner-a');assert.equal(r.conflicts,1);assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'pending');});
test('HTTP error and invalid ACK never mark synced',async t=>{const s=fixture(t),c=await s.create();s.httpError=true;await assert.rejects(s.push.pushMobileCloudNow('owner-a'));s.httpError=false;s.corruptAck=true;await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'invalid_ack'});assert.equal(s.row('categorias',c.category.sync_id).sync_status,'pending');assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'pending');});
test('transaction failure after cloud response rolls back all metadata and retry recovers',async t=>{const s=fixture(t),c=await s.create();s.failAck=true;await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'ack_failed'});assert.equal(s.row('categorias',c.category.sync_id).sync_status,'pending');assert.equal(s.row('categorias',c.category.sync_id).last_remote_revision,null);assert.equal(s.bucket('owner-a').movimientos.size,1);s.failAck=false;await s.push.pushMobileCloudNow('owner-a');assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'synced');assert.equal(s.bucket('owner-a').movimientos.size,1);});
test('edit during request cannot be falsely acknowledged, owner switch retains pending',async t=>{const s=fixture(t),c=await s.create();s.afterSend=async body=>{if(body.movimientos.length)await s.repo('owner-a').updateMovimiento(c.movement.id,{fecha:c.movement.fecha,tipo:'gasto',categoria_id:c.category.id,descripcion:'later edit',monto:77});};const result=await s.push.pushMobileCloudNow('owner-a');assert.equal(result.stillPending,1);assert.equal(s.row('movimientos',c.movement.sync_id).descripcion,'later edit');assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'pending');s.afterSend=null;assert.equal((await s.push.pushMobileCloudNow('owner-a')).conflicts,0);assert.equal(s.row('movimientos',c.movement.sync_id).sync_status,'synced');await s.repo('owner-a').createCategoria({nombre:'Owner switch request',tipo:'gasto'});s.afterSend=async()=>{s.active='owner-b';};await assert.rejects(s.push.pushMobileCloudNow('owner-a'),{code:'owner_changed'});});
test('movement and category tombstones retain sync IDs and cloud mirrors deletion',async t=>{const s=fixture(t),c=await s.create();await s.push.pushMobileCloudNow('owner-a');await s.repo('owner-a').deleteMovimiento(c.movement.id);await s.repo('owner-a').deleteCategoria(c.category.id);const result=await s.push.pushMobileCloudNow('owner-a');assert.equal(result.uploaded,2);for(const [table,id]of [['categorias',c.category.sync_id],['movimientos',c.movement.sync_id]]){assert.ok(s.row(table,id).deleted_at);assert.equal(s.row(table,id).sync_status,'synced');assert.ok(s.bucket('owner-a')[table].get(id).deleted_at);}});
test('v4 normalized baseline is recovered as exact server string without false conflict',async t=>{const s=fixture(t),c=await s.create();await s.push.pushMobileCloudNow('owner-a');s.db.prepare("UPDATE categorias SET last_remote_revision=NULL WHERE sync_id=?").run(c.category.sync_id);await s.repo('owner-a').updateCategoria(c.category.id,{nombre:'Renamed',tipo:'gasto'});assert.equal((await s.push.pushMobileCloudNow('owner-a')).conflicts,0);assert.equal(s.bucket('owner-a').categorias.get(c.category.sync_id).nombre,'Renamed');});
test('scoped writes reject unsupported note/meta without affecting local default',async t=>{const s=fixture(t),c=await s.create();await assert.rejects(s.repo('owner-a').createMovimiento({fecha:'2026-10-06',tipo:'gasto',categoria_id:c.category.id,descripcion:'test',monto:1,nota:'local only'}));assert.equal(s.db.prepare("SELECT COUNT(*) n FROM movimientos WHERE owner_user_id='owner-a'").get().n,1);});

test('rapid push calls coalesce and do not produce a request storm',async t=>{const s=fixture(t);await s.create();let release; s.afterSend=()=>new Promise(r=>release=r);const first=s.push.pushMobileCloudNow('owner-a'),again=s.push.pushMobileCloudNow('owner-a');assert.equal(first,again);while(!release)await new Promise(r=>setImmediate(r));s.afterSend=null;release();await first;assert.equal(s.calls.filter(c=>c.method==='POST').length,2);});
test('Android HTTP UUID fallback remains random, v4, and never uses counters',t=>{const s=fixture(t);const previous=Object.getOwnPropertyDescriptor(globalThis,'crypto');const original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{configurable:true,value:{getRandomValues:original.getRandomValues.bind(original)}});t.after(()=>Object.defineProperty(globalThis,'crypto',previous));const {newSyncId}=require('../services/data/mobileRepositorySupport.ts');const ids=Array.from({length:50},newSyncId);assert.equal(new Set(ids).size,50);for(const id of ids)assert.match(id,/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);});

test('literal category and movement batches can each be resent twice without duplicate cloud IDs',async t=>{const s=fixture(t),c=await s.create();await s.push.pushMobileCloudNow('owner-a');const original=s.calls.filter(call=>call.method==='POST').map(call=>structuredClone(call.body));const cloud=require('../services/cloudAuth.ts');for(const body of original){const ack=await cloud.cloudRequest('/sync/push',{method:'POST',headers:{Authorization:'Bearer grant-fixture'},body:JSON.stringify(body)});assert.equal(ack.rejected.length,0);}assert.equal(s.bucket('owner-a').categorias.size,1);assert.equal(s.bucket('owner-a').movimientos.size,1);assert.ok(s.bucket('owner-a').categorias.has(c.category.sync_id));assert.ok(s.bucket('owner-a').movimientos.has(c.movement.sync_id));});
